services:
  sql:
    image: postgres:17.5-alpine3.22
    container_name: safia-sql
    restart: always
    environment:
      - POSTGRES_DB=db_safia
      - POSTGRES_USER=user_safia
      - POSTGRES_PASSWORD=P455W0RD_S4F14
    ports:
      - 5444:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_safia"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - local-sql:/var/lib/postgres/data
    networks:
      - localnet

  cache:
    image: redis:8.0.3-alpine3.21
    # image: valkey:8-alpine3.22
    # image: memcached:1.6.39-alpine3.22
    container_name: safia-cache
    restart: always
    mem_limit: 1024mb
    ports:
      - 6379:6379
    volumes:
      - local-cache:/data
    networks:
      - localnet

  sonarqube:
    image: sonarqube:lts-community
    container_name: safia-code-quality
    restart: always
    environment:
      - SONAR_LOGIN=safia
      - SONAR_PASSWORD=s0n4r_P455W0RD_S4F14
    ports:
      - 9000:9000
    volumes:
      - local-codequality-data:/opt/sonarqube/data
      - local-codequality-logs:/opt/sonarqube/logs
      - local-codequality-extensions:/opt/sonarqube/extensions
    networks:
      - localnet
    # token: sqp_67c73551a443a9fa2d849c51999d47339786f686

# Application - SAF.IA
  # app:
  #   image: openjdk21
  #   container_name: safia
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     cache_from:
  #       - openjdk21
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 50m
  #       max-file: 5
  #   ports:
  #     - 8080:8080
  #     - 8433:8433
    # healthcheck:
    #   test: ["curl", "pg_isready", "-d", "db_safia"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
  #   depends_on:
  #     safia-cache:
  #       condition: service_healthy
  #     safia-sql:
  #       condition: service_healthy

networks:
  localnet:
    driver: bridge

volumes:
  local-sql:
  local-cache:
  local-codequality-data:
  local-codequality-logs:
  local-codequality-extensions:
