spring:
  application:
    name: sofia

  # cache:
  #   redis:
  #     key-prefix: "sofia:"
  #     time-to-live: 20000
  #     cache-null-values: false
  #     use-key-prefix: true

  # data:
  #   redis:
  #     database: 0
  #     host: localhost
  #     port: 6379
  #     client-name: sofia-cache
  #     username: default
  #     connect-timeout: 60000


  datasource:
    url: jdbc:postgresql://localhost:5444/db_sofia
    username: user_sofia
    password: P455W0RD_S0F14

    hikari:
      maximum-pool-size: 20

  jpa:
    properties:
      hibernate:
        format-sql: true
        jdbc:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    # database: postgresql
    # generate-ddl: false
    # show-sql: true
    # hibernate:
    #   ddl-auto: false

  security:
    user:
      name: admin
      password: SPR1NG_4DM1N

server:
  port: 8080
