logging:
  log4j2:
    config:
      override:
      -  log4j2-spring.xml

spring:
  application:
    name: safia
    version: 1.0.0

  # cache:
  #   redis:
  #     key-prefix: "safia:"
  #     time-to-live: 20000
  #     cache-null-values: false
  #     use-key-prefix: true

  # data:
  #   redis:
  #     database: 0
  #     host: localhost
  #     port: 6379
  #     client-name: safia-cache
  #     username: default
  #     connect-timeout: 60000

  datasource:
    url: jdbc:postgresql://localhost:5444/db_safia
    username: user_safia
    password: P455W0RD_S4F14
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: safia-connection-pool
      max-lifetime: 1800000
      maximum-pool-size: 20

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        format-sql: true
        ddl-auto: none
        generate_statistics: true

  lifecycle:
    timeout-per-shutdown-phase: "30s"

  security:
    user:
      name: admin
      password: SPR1NG_4DM1N
      roles:
      - ADMIN

management:
  observations:
    annotations:
      enabled: true
    key-values:
      region: "south-america-1"
      stack: "dsv"
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8080

  tomcat:
    max-connections: 256
    threads:
      max: 20

  error:
    whitelabel:
      enabled: true
    # include-message: never
    # include-stacktrace: never
